filter:
  paths: [ "vendor/*" ]
  excluded_paths: [ "vendor/*", "FacturaScripts/", ]
build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
      environment:
        php:
          version: 8.2