<?php
/*
 * Copyright (C) 2022 Joe Nilson <joenilson@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

namespace FacturaScripts\Plugins\fsRepublicaDominicana\Model\Join;

use FacturaScripts\Core\Model\Base\JoinModel;

class FiscalReport606 extends JoinModel
{
    const MAIN_TABLE = 'facturasprov';
    const LINES_TABLE = 'lineasfacturasprov';
    const SECONDARY_TABLE = 'facturasprov AS f2';
    const SECONDARY_TABLE_ALIAS = 'f2';
    const ESTADOSDOC_TABLE = 'estados_documentos';
    const PRODS_TABLE = 'productos';

    /**
     *
     * @return array
     */
    protected function getFields(): array
    {
        $dateFormat = (FS_DB_TYPE === 'postgresql') ? "to_char" : "date_format";
        $dateFormatString = (FS_DB_TYPE === 'postgresql') ? "YYYYMMDD" : "%Y%m%d";

        $data = [
            'itemrow' => static::MAIN_TABLE.'.idfactura',
            'idempresa' => static::MAIN_TABLE.'.idempresa',
            'codalmacen' => static::MAIN_TABLE.'.codalmacen',
            'cifnif' => 'CASE WHEN length('.static::MAIN_TABLE.'.cifnif)=9 THEN '.static::MAIN_TABLE.'.cifnif WHEN length('.static::MAIN_TABLE.'.cifnif)=11 THEN '.static::MAIN_TABLE.'.cifnif ELSE NULL END',
            'tipoid' => 'CASE WHEN length('.static::MAIN_TABLE.'.cifnif)=9 THEN 1 WHEN length('.static::MAIN_TABLE.'.cifnif)=11 THEN 2 ELSE 3 END',
            'tipocompra' => static::MAIN_TABLE.'.ncftipomovimiento',
            'ncf' => static::MAIN_TABLE.'.numproveedor',
            'ncfmodifica' => static::SECONDARY_TABLE_ALIAS.'.numproveedor',
            'fecha' => $dateFormat.'('.static::MAIN_TABLE.'.fecha,\''.$dateFormatString.'\')',
            'fechapago' => '\'\'',
            'totalservicios' => 'SUM(CASE WHEN '.static::PRODS_TABLE.'.esservicio = true THEN '.static::LINES_TABLE.'.pvptotal ELSE 0 END)',
            'totalbienes' => 'SUM(CASE WHEN '.static::PRODS_TABLE.'.esservicio = false THEN '.static::LINES_TABLE.'.pvptotal ELSE 0 END)',
            'base' => 'CASE WHEN '.static::ESTADOSDOC_TABLE.'.nombre = \'Anulada\' THEN 0 WHEN '.static::ESTADOSDOC_TABLE.'.nombre = \'Emitida\' AND '.static::MAIN_TABLE.'.neto < 0 THEN '.static::MAIN_TABLE.'.neto*-1 ELSE '.static::MAIN_TABLE.'.neto END',
            'itbis' => 'CASE WHEN '.static::ESTADOSDOC_TABLE.'.nombre = \'Anulada\' THEN 0 WHEN '.static::ESTADOSDOC_TABLE.'.nombre = \'Emitida\' AND '.static::MAIN_TABLE.'.totaliva < 0 THEN '.static::MAIN_TABLE.'.totaliva*-1 ELSE '.static::MAIN_TABLE.'.totaliva END',
            'itbisretenido' => '0',
            'itbissujeto' => '0',
            'itbisalcosto' => '0',
            'itbisporadelantar' => '0',
            'itbispercibido' => '0',
            'tiporetencionrenta' => '\'\'',
            'rentaretenido' => '0',
            'rentapercibido' => '0',
            'isc' => '0',
            'otrosimpuestos' => '0',
            'propinalegal' => '0',
            'tipopago' => 'CASE WHEN '.static::MAIN_TABLE.'.ncftipomovimiento is null THEN \'02\' ELSE '.static::MAIN_TABLE.'.ncftipomovimiento END',
            'estado' => 'CASE WHEN '.static::ESTADOSDOC_TABLE.'.nombre = \'Emitida\' THEN \'Activo\' ELSE \'Anulado\' END',
        ];
        return $data;
    }

    protected function getGroupFields(): string
    {
        //return parent::getGroupFields(); // TODO: Change the autogenerated stub
        return  static::MAIN_TABLE.'.idfactura, ' .
                static::MAIN_TABLE.'.idempresa, ' .
                static::MAIN_TABLE.'.codalmacen, ' .
                static::MAIN_TABLE.'.cifnif, ' .
                static::MAIN_TABLE.'.ncftipomovimiento, ' .
                static::MAIN_TABLE.'.numproveedor, ' .
                static::SECONDARY_TABLE_ALIAS.'.numproveedor, ' .
                static::MAIN_TABLE.'.fecha, ' .
                static::ESTADOSDOC_TABLE.'.nombre, ' .
                static::MAIN_TABLE.'.neto, ' .
                static::MAIN_TABLE.'.totaliva' .
            ' ';
    }

    /**
     *
     * @return string
     */
    protected function getSQLFrom(): string
    {
        return static::MAIN_TABLE
            . ' LEFT JOIN '. static::SECONDARY_TABLE . ' ON ('
            . static::MAIN_TABLE . '.idfacturarect = ' . static::SECONDARY_TABLE_ALIAS . '.idfactura)'
            . ' LEFT JOIN '. static::LINES_TABLE . ' ON ('
            . static::MAIN_TABLE . '.idfactura = ' . static::LINES_TABLE . '.idfactura)'
            . ' LEFT JOIN '. static::PRODS_TABLE . ' ON ('
            . static::LINES_TABLE . '.referencia = ' . static::PRODS_TABLE . '.referencia)'
            . ' LEFT JOIN ' . static::ESTADOSDOC_TABLE . ' ON ('
            . static::MAIN_TABLE . '.idestado = ' . static::ESTADOSDOC_TABLE . '.idestado)';
    }

    /**
     *
     * @return array
     */
    protected function getTables(): array
    {
        return [
            static::MAIN_TABLE,
            static::LINES_TABLE,
            static::ESTADOSDOC_TABLE,
            static::PRODS_TABLE
        ];
    }
}
